#include "AssessedProblem.h"
#include <cmath>
#include <iostream>
#include <vector>

// Print out the current charges and dipole moments
void printSystem(std::vector<pointCharge> charges, std::vector<dipole> dipoles){
    std::cout << "\nPoint charges";
    std::cout << "\nPosition z / Angstrom    Charge q / e";
    for(int i=0; i<charges.size(); i++){
        std::cout << "\n" << charges[i].getPosition() << "    " << charges[i].getCharge();
    }
    std::cout << "\n\nDipoles";
    std::cout << "\nPosition z / Angstrom    Dipole moment mu / D";
    for(int i=0; i<dipoles.size(); i++){
        std::cout << "\n" << dipoles[i].getPosition() << "    " << dipoles[i].getMoment();
    }
    std::cout << "\n";
}

// Displacement vector from position1 to position2 (in one dimension, this is just the difference)
double displacement(double position1, double position2){
    double disp = position2 - position1;
    return disp;
}

// Dot product between two vectors (in one dimension, this is just the product)
double dotproduct(double vector1, double vector2){
    double prod = vector1 * vector2;
    return prod;
}

// Magnitude of a vector
double magnitude(double vector){
    return sqrt(dotproduct(vector, vector));
}

// Electrostatic potential at a given position generated by a given point charge
double pointChargePotential(double position, pointCharge pointCharge_){
    double dist = magnitude(displacement(pointCharge_.getPosition(), position));
    return pointCharge_.getCharge() / dist;
}

// Electrostatic potential at a given position generated by a given dipole
double dipolePotential(double position, dipole dipole_){
    double disp = displacement(dipole_.getPosition(), position);
    double dist = magnitude(disp);
    return dotproduct(dipole_.getMoment(), disp) / pow(dist, 3);
}

// Electric field at a given position generated by a given point charge
double pointChargeField(double position, pointCharge pointCharge_){
    double disp = displacement(pointCharge_.getPosition(), position);
    double dist = magnitude(disp);
    return pointCharge_.getCharge() * disp / pow(dist, 2);
}

// Electric field at a given position generated by a given dipole
double dipoleField(double position, dipole dipole_){
    double disp = displacement(dipole_.getPosition(), position);
    double dist = magnitude(disp);
    return 2 * dipole_.getMoment() / pow(dist, 3);
}

// Calculate the field experienced by each point charge and dipole produced by the rest of the system
void calculateFields(std::vector<pointCharge> &charges, std::vector<dipole> &dipoles, double externalField){
    std::vector<dipole> oldDipoles = dipoles;
    double position, field;
    for (int i=0; i<dipoles.size(); i++){
        position = oldDipoles[i].getPosition();
        field = externalField;
        for (int j=0; j<charges.size(); j++){
            if (position != charges[j].getPosition()){
                field += pointChargeField(position, charges[j]);
            }
        }
        for (int j=0; j<dipoles.size(); j++){
            if (position != dipoles[j].getPosition()){
                field += dipoleField(position, oldDipoles[j]);
            }
        }
        dipoles[i].setField(field);
    }
}

// Update dipoles based on the field they experience, returning the largest absolute change in dipole moment
double updateDipoles(std::vector<dipole> &dipoles, double staticMoment){
    double oldMoment, newMoment, polarisability, field;
    double change = 0;
    for (int i=0; i<dipoles.size(); i++){
        oldMoment = dipoles[i].getMoment();
        polarisability = dipoles[i].getPolarisability();
        field = dipoles[i].getField();
        newMoment = staticMoment + polarisability * field;
        if (magnitude(change) < magnitude(newMoment - oldMoment)){
            change = newMoment - oldMoment;
        }
        dipoles[i].setMoment(newMoment);
    }
    return magnitude(change);
}

int main(int argc, char *argv[]){
    // Default parameters for 1d lattice of identical charges and 1d lattice of identical dipoles
    double externalPotential = 0.;
    double externalField = 0.;
    int nCharges = 0;
    int nDipoles = 0;
    double chargeLatticeSeparation = 0.;
    double dipoleLatticeSeparation = 0.;
    double charge = 0.;
    double polarisability = 0.;
    double staticMoment = 0.;

    // Read command line arguments to update parameters
    for (int i=1; i<argc; i+=2 ){
        std::string flag = std::string(argv[i]);
        std::string value = std::string(argv[i+1]);
        if (flag == "-nc"){
            nCharges = stoi(value);
        } else if (flag == "-nd"){
            nDipoles = stoi(value);
        } else if (flag == "-cl"){
            chargeLatticeSeparation = stod(value);
        } else if (flag == "-dl"){
            dipoleLatticeSeparation = stod(value);
        } else if (flag == "-c"){
            charge = stod(value);
        } else if (flag == "-p"){
            polarisability = stod(value);
        } else if (flag == "-m"){
            staticMoment = stod(value);
        } else if (flag == "-f"){
            externalField = stod(value);
        }
    }

    // Place charges in 1d lattice, with first charge at 0
    std::vector<pointCharge> charges(nCharges);
    for(int i=0; i<nCharges; i++){
        charges[i].setPosition(i*chargeLatticeSeparation);
        charges[i].setPotential(externalPotential);
        charges[i].setField(externalField);
        charges[i].setCharge(charge);
    }

    // Place dipoles, with first dipole at 1 * dipoleLatticeSeparation
    std::vector<dipole> dipoles(nDipoles);
    for(int i=0; i<nDipoles; i++){
        dipoles[i].setPosition((i+1)*dipoleLatticeSeparation);
        dipoles[i].setPotential(externalPotential);
        dipoles[i].setField(externalField);
        dipoles[i].setPolarisability(polarisability);
        dipoles[i].setMoment(staticMoment);
    }

    double dipoleChange;
    int i = 0, maxIterations = 1000;
    while(i < maxIterations){
        printSystem(charges, dipoles);
        calculateFields(charges, dipoles, externalField);
        dipoleChange = updateDipoles(dipoles, staticMoment);
        std::cout << "\n" << dipoleChange;
        if (dipoleChange < pow(10, -4)){
            return 0;
        }
        i++;
    }
    std::cout << "Dipoles not converged in " << maxIterations << " steps.";
    return 1;
}